# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d128dc55b6869f978b283c8920e91729bc7075bd20a3d3743b322c1a1ef28dcab087941227c7b176832c80b0c86721d04ce6779aadcf877ed65f1d349765ec1

test:
  secret_key_base: 5d56be8bc7bb296f02406cf35bc096ab04a97e5a5b669ade95171d7c84dd8a28ca81f4039c9de6e4e684c7a2f48904f37e5a75e87c1e210ce741edb9289f7b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
